"""Replace requested_by with staff_id in LabTest

Revision ID: 804f02bc5a7e
Revises: 333090f891a6
Create Date: 2025-07-23 12:44:42.224472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804f02bc5a7e'
down_revision: Union[str, None] = '333090f891a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labtest', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('labtest_requested_by_fkey'), 'labtest', type_='foreignkey')
    op.create_foreign_key(None, 'labtest', 'staff', ['staff_id'], ['id'])
    op.drop_column('labtest', 'requested_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labtest', sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'labtest', type_='foreignkey')
    op.create_foreign_key(op.f('labtest_requested_by_fkey'), 'labtest', 'staff', ['requested_by'], ['id'])
    op.drop_column('labtest', 'staff_id')
    # ### end Alembic commands ###
