"""special care assignments table 2

Revision ID: 8e102ca7a5d7
Revises: 34b51742dcb1
Create Date: 2025-04-17 11:46:48.560709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8e102ca7a5d7'
down_revision: Union[str, None] = '34b51742dcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_care_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('unit_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('specialcareassignment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialcareassignment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name='specialcareassignment_patient_id_fkey'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name='specialcareassignment_staff_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='specialcareassignment_pkey')
    )
    op.drop_table('special_care_assignment')
    # ### end Alembic commands ###
