"""Add email_sent and reminder_sent to Appointment

Revision ID: a31e28b54c6f
Revises: 4ca944b7b1d0
Create Date: 2025-07-16 16:47:46.674560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31e28b54c6f'
down_revision: Union[str, None] = '4ca944b7b1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('email_sent', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('appointment', sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'reminder_sent')
    op.drop_column('appointment', 'email_sent')
    # ### end Alembic commands ###
