"""Made requested_by and lab_id optional on lab_test model

Revision ID: a41122fabe50
Revises: a31e28b54c6f
Create Date: 2025-07-18 13:45:51.860880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41122fabe50'
down_revision: Union[str, None] = 'a31e28b54c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labtest', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('labtest', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labtest', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('labtest', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
