"""Added diagnosis to lab tests

Revision ID: d0a76acf15b7
Revises: a57017d2cc43
Create Date: 2025-07-21 12:22:39.406030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0a76acf15b7'
down_revision: Union[str, None] = 'a57017d2cc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labtest', sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labtest', 'diagnosis')
    # ### end Alembic commands ###
